// Generated by https://quicktype.io

export interface AxiosCybershoke {
    result: string;
    stats: Stats;
    servers: Servers;
    modes: { [key: string]: ModeClass };
    listmodes: { [key: string]: ListmodeValue };
}

export enum ListmodeValue {
    Aimdm = "AIMDM",
    Amongus = "AMONGUS",
    Arena = "ARENA",
    Awp = "AWP",
    Awpdm = "AWPDM",
    Bhop = "BHOP",
    Deathrun = "DEATHRUN",
    Dm = "DM",
    Duels = "DUELS",
    Duels2X2 = "DUELS2X2",
    Execute = "EXECUTE",
    Hns = "HNS",
    Hsdm = "HSDM",
    Jail = "JAIL",
    Knife = "KNIFE",
    Kz = "KZ",
    Maniac = "MANIAC",
    Minigames = "MINIGAMES",
    Multicfgdm = "MULTICFGDM",
    Pistoldm = "PISTOLDM",
    Pistolretake = "PISTOLRETAKE",
    Prophunt = "PROPHUNT",
    Public = "PUBLIC",
    Retake = "RETAKE",
    Retakeclassic = "RETAKECLASSIC",
    Shokelobby = "SHOKELOBBY",
    Surf = "SURF",
    Surfcombat = "SURFCOMBAT",
    Zombieescape = "ZOMBIEESCAPE",
}

export interface ModeClass {
    name: Name;
    servers: number;
    players: number;
    maxplayers: number;
    prime: number;
    noprime: number;
    type: Type;
    releaseDate: null;
}

export enum Name {
    Aimdm = "AIMDM",
    AmongUs = "AMONG US",
    Arena = "ARENA",
    Awp = "AWP",
    Awpdm = "AWPDM",
    Bhop = "BHOP",
    Chill = "CHILL",
    Deathrun = "DEATHRUN",
    Dm = "DM",
    Duels = "DUELS",
    Duels2X2 = "DUELS 2X2",
    Execute = "EXECUTE",
    Hns = "HNS",
    Hsdm = "HSDM",
    Jail = "JAIL",
    Knife = "KNIFE",
    Kz = "KZ",
    Maniac = "MANIAC",
    Minigames = "MINIGAMES",
    MulticfgDm = "MULTICFG DM",
    PistolRetake = "PISTOL RETAKE",
    Pistoldm = "PISTOLDM",
    Prophunt = "PROPHUNT",
    Public = "PUBLIC",
    Retake = "RETAKE",
    RetakeClassic = "RETAKE CLASSIC",
    Surf = "SURF",
    SurfCombat = "SURF COMBAT",
    ZombieEscape = "ZOMBIE ESCAPE",
}

export enum Type {
    Gold = "gold",
    Primary = "primary",
}

export interface Servers {
    AIMDM: Aimdm;
    AMONGUS: Amongus;
    ARENA: Amongus;
    AWP: Awp;
    AWPDM: Awpdm;
    BHOP: { [key: string]: LivingstoneSouthernWhiteFacedOwl[] };
    DEATHRUN: Deathrun;
    DM: { [key: string]: LivingstoneSouthernWhiteFacedOwl[] };
    DUELS: Duels;
    DUELS2X2: Duels;
    EXECUTE: Amongus;
    HNS: Hns;
    HSDM: Hsdm;
    JAIL: { [key: string]: LivingstoneSouthernWhiteFacedOwl[] };
    KNIFE: Amongus;
    KZ: { [key: string]: LivingstoneSouthernWhiteFacedOwl[] };
    MANIAC: Amongus;
    MINIGAMES: Minigames;
    MULTICFGDM: Amongus;
    PISTOLDM: Pistoldm;
    PISTOLRETAKE: Pistolretake;
    PROPHUNT: Amongus;
    PUBLIC: { [key: string]: LivingstoneSouthernWhiteFacedOwl[] };
    RETAKE: { [key: string]: LivingstoneSouthernWhiteFacedOwl[] };
    RETAKECLASSIC: { [key: string]: LivingstoneSouthernWhiteFacedOwl[] };
    SHOKELOBBY: Amongus;
    SURF: { [key: string]: LivingstoneSouthernWhiteFacedOwl[] };
    SURFCOMBAT: Amongus;
    ZOMBIEESCAPE: Amongus;
}

export interface Aimdm {
    AIMDM: LivingstoneSouthernWhiteFacedOwl[];
    "PISTOL AIMDM": LivingstoneSouthernWhiteFacedOwl[];
}

export interface LivingstoneSouthernWhiteFacedOwl {
    id: number;
    name_alt: string;
    ip: string;
    port: number;
    mode: ListmodeValue;
    modeAlt: Name;
    num: number;
    location: Location;
    country: Country;
    map: string;
    prime: number;
    players: number;
    maxplayers: number;
    status: Status;
    faceit_avg: number;
    show_maps_avg_time: number;
    statusAlt: number;
    category: string;
    time_avg_complete: number | null;
    faceit_limiter_enable: number;
    faceit_min_elo: number | null;
    faceit_max_elo: number | null;
}

export enum Country {
    De = "de",
    Fi = "fi",
    Fr = "fr",
    Kz = "kz",
    Pl = "pl",
    Ru = "ru",
    SE = "se",
    Ua = "ua",
}

export enum Location {
    DathostFr = "dathost-fr",
    DathostUaWarsaw = "dathost-ua-warsaw",
    Ekb = "ekb",
    Helsinki = "helsinki",
    HiperzEu = "hiperz-eu",
    Kazakhstan = "kazakhstan",
    Kiev = "kiev",
    Myarena = "myarena",
    Nv = "nv",
    Sweden = "sweden",
}

export enum Status {
    Online = "Online",
}

export interface Amongus {
    "": LivingstoneSouthernWhiteFacedOwl[];
}

export interface Awp {
    "AWP CANNONS": LivingstoneSouthernWhiteFacedOwl[];
    "ONLY AWP LEGO 2": LivingstoneSouthernWhiteFacedOwl[];
    "AWP SERVERS": LivingstoneSouthernWhiteFacedOwl[];
}

export interface Awpdm {
    "AWPDM LITE": LivingstoneSouthernWhiteFacedOwl[];
    AWPDM: LivingstoneSouthernWhiteFacedOwl[];
    NOSCOPEDM: LivingstoneSouthernWhiteFacedOwl[];
}

export interface Deathrun {
    EASY: LivingstoneSouthernWhiteFacedOwl[];
    NORMAL: LivingstoneSouthernWhiteFacedOwl[];
    WARMUP: LivingstoneSouthernWhiteFacedOwl[];
}

export interface Duels {
    "ONLY MIRAGE": LivingstoneSouthernWhiteFacedOwl[];
    "ONLY DUST2": LivingstoneSouthernWhiteFacedOwl[];
    "ALL MAPS": LivingstoneSouthernWhiteFacedOwl[];
}

export interface Hns {
    "HNS NO RULES": LivingstoneSouthernWhiteFacedOwl[];
    "HNS SERVERS": LivingstoneSouthernWhiteFacedOwl[];
    "HNS TRAINING": LivingstoneSouthernWhiteFacedOwl[];
}

export interface Hsdm {
    "HSDM LITE": LivingstoneSouthernWhiteFacedOwl[];
    HSDM: LivingstoneSouthernWhiteFacedOwl[];
    "HSDM ONETAP": LivingstoneSouthernWhiteFacedOwl[];
}

export interface Minigames {
    "FUN MAPS": LivingstoneSouthernWhiteFacedOwl[];
    "BATTLE MAPS": LivingstoneSouthernWhiteFacedOwl[];
}

export interface Pistoldm {
    "PISTOL HSDM": LivingstoneSouthernWhiteFacedOwl[];
    "PISTOLDM LITE": LivingstoneSouthernWhiteFacedOwl[];
    PISTOLDM: LivingstoneSouthernWhiteFacedOwl[];
}

export interface Pistolretake {
    "9 SLOTS": LivingstoneSouthernWhiteFacedOwl[];
}

export interface Stats {
    countPlayers: number;
    countPlayers24h: number;
    countNewPlayers24h: number;
    countServers: number;
    countModes: number;
    countPlayersOnServers: number;
    countMaxPlayersOnServers: number;
}
